### PR TITLE
Store ZDT with a UTC, not local, timestamp

### LINKED ISSUE #327: DST ambiguities in ZonedDateTime not supported
It seems like the ArrowTypes representation of ZonedDateTime doesn't include enough information to resolve ambiguities around DST, e.g.:

```julia
julia> zdt = ZonedDateTime(DateTime(2020, 11, 1, 6), tz"America/New_York"; from_utc=true)
2020-11-01T01:00:00-05:00

julia> arrow_zdt = ArrowTypes.toarrow(zdt)
Arrow.Timestamp{Arrow.Flatbuf.TimeUnits.MILLISECOND, Symbol("America/New_York")}(1604192400000)

julia> ArrowTypes.fromarrow(ZonedDateTime, arrow_zdt)
ERROR: AmbiguousTimeError: Local DateTime 2020-11-01T01:00:00 is ambiguous within America/New_York
Stacktrace:
 [1] (::TimeZones.var"#construct#8"{DateTime, VariableTimeZone})(T::Type{Local})
   @ TimeZones ~/.julia/packages/TimeZones/X0cjt/src/types/zoneddatetime.jl:46
 [2] #ZonedDateTime#7
   @ ~/.julia/packages/TimeZones/X0cjt/src/types/zoneddatetime.jl:50 [inlined]
 [3] ZonedDateTime
   @ ~/.julia/packages/TimeZones/X0cjt/src/types/zoneddatetime.jl:37 [inlined]
 [4] convert(#unused#::Type{ZonedDateTime}, x::Arrow.Timestamp{Arrow.Flatbuf.TimeUnits.MILLISECOND, Symbol("America/New_York")})
   @ Arrow ~/.julia/packages/Arrow/ZlMFU/src/eltypes.jl:265
 [5] fromarrow(#unused#::Type{ZonedDateTime}, x::Arrow.Timestamp{Arrow.Flatbuf.TimeUnits.MILLISECOND, Symbol("America/New_York")})
   @ Arrow ~/.julia/packages/Arrow/ZlMFU/src/eltypes.jl:300
 [6] top-level scope
   @ REPL[16]:1
```

Knowing very little about how how we're constrained within the arrow spec, can this be fixed by storing the UTC timestamp? I'm _guessing_ we're running into this as we're storing a local timestamp + the timezone (?), which isn't quite enough information.

### PR DESCRIPTION
**Pull request by tpgillam**
Closes #327 

This changes the representation of zone-aware datetimes to store a UTC timestamp + zone. Previously Arrow.jl used the _local_ timestamp + zone, which leads to ambiguity failures around DST changes. More importantly, it seems like this change is required to be consistent with the standard (see discussion [here](https://github.com/apache/arrow-julia/issues/327#issuecomment-1169090020))

If this is indeed the appropriate fix, I'd appreciate thoughts on how we can make this change safely / with minimal disruption!

* This is clearly a breaking change, in that any new version of Arrow.jl will be incompatible with arrow files (containing zone-aware datetimes) written with older versions of Arrow.jl.

* Other than changing the package version in the usual way, is there any other kind of version info that's available? I'm wondering if it's possible prevent users from loading a file written with an older / incompatible version of Arrow.jl

* I noticed a `pyarrow_rountrip.jl` file in the tests. I was hoping that this might provide some mechanism to test for interop wrt. zoned datetimes. However, I'm actually not sure that this is its purpose (it doesn't seem to be run as part of CI, or indeed have any `@test`s. Can someone (@quinnj ? ) indicate if this kind of test is possible right now please? Thanks!

### CODE REVIEW

**Comment by ericphanson** [comment]
I've made a PR in https://github.com/tpgillam/arrow-julia/pull/1 to try to make this change backwards compatible.

**Comment by tpgillam** [comment]
I'm also wondering about how (if at all) the native `Timestamp` logic interacts with any of this. For example here:

https://github.com/apache/arrow-julia/blob/52bfe1f72fa72b0b2d150efeeeb9edacd853f96f/src/metadata/Schema.jl#L319-L336

I _think_ (based on #303 ) that native-arrow-time-with-timezone should *somewhere* get converted to a `ZonedDateTime` on reading, but can't figure out if that's a different code path, or is also affected by the issue.

**Comment by snakch** [comment]
Just bumping this - I'm running into the same issue

**Comment by nickrobinson251** [comment]
this looks fine to me -- @tpgillam could you merge in https://github.com/tpgillam/arrow-julia/pull/1 and convert this PR from draft?

**Comment by tpgillam** [comment]
@nickrobinson251 I have rebased this PR on the latest `main` - so should be good for a test run & hopefully merging now.

**Review by nickrobinson251 — APPROVED** [review]
Seems good to me! 

Thanks, @tpgillam and @ericphanson!

@quinnj good to merge?

**Pull request merged**
