### PR TITLE
Bump version to 2.4.0

### PR DESCRIPTION
**Pull request by baumgold**
@kou / @quinnj - can we start a new minor version release process, please?  Thanks!

### CODE REVIEW

**Comment by ericphanson** [comment]
I think Arrow 2.3.0 was manually registered (https://github.com/JuliaRegistries/General/pull/58479) which did not trigger tagbot (bc manual PRs to the registry don't trigger the tagbot workflow I guess). We could update our tagbot config to allow a configurable look-back parameter (https://github.com/JuliaRegistries/TagBot#setup), then manually trigger tagbot (via workflow dispatch) with a long lookback to try to pick up that release.

**Comment by ericphanson** [comment]
Sure, that would work too. (The thing I was suggesting would also make it so we have a 2.3.0 release showing up in github).

**Review by quinnj — APPROVED** [review]

**Comment by kou** [comment]
The vote thread: https://lists.apache.org/thread/o55x29wcosxsld2mt8jo28nk5jj47nff

**Comment by kou** [comment]
@quinnj Now, you can cast a binding vote as a new PMC member: https://lists.apache.org/thread/3fyckbljtn38nc54cm75d8owoxkm1p3r

**Comment by kou** [comment]
@quinnj The vote carried: https://lists.apache.org/thread/pz1go0czw9y51qppfwd493dzssxsxx04
I've published the voted archive to https://dist.apache.org/repos/dist/release/arrow/arrow-julia-2.4.0/ .

Could you publish this release to the Julia General registry?

**Comment by ericphanson** [comment]
I gave it a try with https://github.com/apache/arrow-julia/commit/571a8fcf6866956d6a47390769e765d1ed0782c7#commitcomment-88004839 but I forgot, I don't think the JuliaRegistrator app is installed. I guess we need to do the manual PR like https://github.com/JuliaRegistries/General/pull/58377#issuecomment-1097185560. I've gone ahead and made a PR here: https://github.com/JuliaRegistries/General/pull/71131. Once that is merged, the version is registered in the Julia registry.

**Comment by quinnj** [comment]
I don't think we need to install JuliaRegistrator, but it does require you to be a "public" member of the organization ([here](https://github.com/orgs/apache/people)), so I _think_ it should work if I do it (as I was just added to the list as an Arrow PMC member). The reason we had to do it manually last time was because of a hiccup with having the ArrowTypes subdirectory package and JuliaRegistrator dying because we already had an ArrowTypes version 2.0.0 and we were trying to register Arrow 2.0.0, but Registrator saw there was already a 2.0.0 tag in the repo. I might have the details there reversed, but I believe we should be able to publicly register going forward.

**Comment by kou** [comment]
FYI: @ericphanson you need to configure gitbox.apache.org to be listed in the apache organization members. See the invitation e-mail for details.

**Comment by ericphanson** [comment]
@quinnj do you want to try it? Would be nice to know that it works. I've marked my [manual PR](https://github.com/JuliaRegistries/General/pull/71131) as draft in the meantime.

> FYI: @ericphanson you need to configure gitbox.apache.org to be listed in the apache organization members. See the invitation e-mail for details.


Thank you, I will try that.

**Comment by ericphanson** [comment]
> I don't think we need to install JuliaRegistrator

I think we do if we want to use the comment-based API (the `@JuliaRegistrator register`) but we can use the web API: https://juliahub.com/ui/Registrator. I am now a public member, so I'll try that.

**Comment by baumgold** [comment]
@ericphanson - I’m a bit confused what the status is here. Can you please help me understand what needs to happen to get this new version registered? Is there anything I can do to help? Thanks.

**Comment by ericphanson** [comment]
@baumgold OK, I just merged https://github.com/JuliaRegistries/General/pull/71131, so the version is now released. I was hoping we could figure out how to make the automatic system work, but I think there are difficulties there. I suspect the best way is if we can install the Registrator.jl app on the arrow-julia repository. I am guessing there is an official apache process for this but I don't know what it is.

**Pull request merged**
