### PR TITLE
Pre-allocate buffer

### PR DESCRIPTION
**Pull request by JoaoAparicio**
If we let transcode to its own allocation it will allocate a small vector, start filling it, resize the vector, fill it some more, resize the vector, etc.

Instead in this commit we pre-allocate a vector of the corect size and pass it to transcode().

Inspired by https://github.com/apache/arrow-julia/pull/399

### CODE REVIEW

**Comment by JoaoAparicio** [comment]
Waiting on release of 
https://github.com/JuliaIO/TranscodingStreams.jl/pull/136

**Comment by Moelf** [comment]
any thoughts on:
- https://github.com/apache/arrow-julia/issues/340

?

**Comment by JoaoAparicio** [comment]
I have some thoughts. One solution to "my dataset is larger than memory" is partitioning. If your dataset is partitioned in such a way that each partition fits in memory, you can iterate it with
```
stream = Arrow.Stream(path)
for tbl in stream
    ...
end
```
You can do this right now without requiring any additional features from this package.

In contrast what is discussed in #340 (which is: don't decompress if you don't have to) is a different approach, but doesn't yet exist.

Currently I have some commits that add the feature to multi-thread decompression at the buffer level. I will be trying to upstream what I have so far. The difficulty is that these commits touch a lot of code, so this won't happen overnight. I imagine couple of weeks? On top of that it should be straightforward to implement what is discussed in #340.

**Comment by Moelf** [comment]
```
stream = Arrow.Stream(path)
for tbl in stream
```

the problem of this approach is it's decompressing every branch. Consider examples such as:
- https://github.com/apache/arrow-julia/issues/417

decompressing every branch would be super slower

**Comment by ericphanson** [comment]
nope, LGTM!

**Pull request merged**
