### PR TITLE
Proposal: change `@scopedenum` to make modules to avoid type piracy

### PR DESCRIPTION
**Pull request by NHDaly**
This changes the result of `@scopedenum` to produce a module instead of trying to stick the enums into the enum type, as a proposed fix for https://github.com/JuliaData/Arrow.jl/issues/266.

It's admittedly less pretty, but I think it's still pretty nice! It seems like a hopefully somewhat understandable pattern to follow, which is that it pluralizes your enum name to make a module. We communicate that to the users by returning it at the end of the expression:
```julia
julia> Arrow.FlatBuffers.@scopedenum MyEnum X=1 Y=2
Main.MyEnums

julia> MyEnums.X
X::MyEnum = 1
```

I can see why this is less appealing than what was there before, but what is there before suffers from the performance problems identified in https://github.com/JuliaData/Arrow.jl/issues/266.

Thanks for your consideration! ❤️

### CODE REVIEW

**Comment by NHDaly** [comment]
Verifying this fixes https://github.com/JuliaData/Arrow.jl/pull/267:
```julia
julia> using BenchmarkTools

julia> @btime sort!([rand([Int,Float64,Int8,Int32]) for _ in 1:100], by=fieldcount);
  59.247 μs (103 allocations: 12.33 KiB)

julia> using Arrow
[ Info: Precompiling Arrow [69666777-d1a9-59fb-9406-91d4454c9d45]

julia> @btime sort!([rand([Int,Float64,Int8,Int32]) for _ in 1:100], by=fieldcount);
  53.731 μs (103 allocations: 12.33 KiB)
```

**Comment by ericphanson** [comment]
btw @NHDaly this looks like a great change to me (although I'm not very familiar with the code in question), but FYI commits are frozen for now while they transfer the repo to apache's org (ref https://github.com/JuliaData/Arrow.jl/issues/265)

**Comment by NHDaly** [comment]
:o oh shoot, thanks @ericphanson! Very interesting. Makes sense.

Thanks. So, should we wait until all that is done? Do you know how long that will take? In the meantime, I think we'll do our prototyping against my fork from which i made this PR, which should keep us unblocked for now i guess...?

**Comment by ericphanson** [comment]
Maybe @quinnj knows about the timeline? I don't know myself, sorry.

Developing against the fork makes sense to me. As an alternative, if it will be awhile, I have an idea that I have never tried but I think might work. If you have a private registry you could register your fork there (with the same name + uuid). The way the package manager works is it will take versions from any install registry. So you could do something like register patches like `v"2.2.1"` , `v"2.2.2"`, etc from your fork into your private registry, and then ask for the next release of this Arrow.jl to be `v"2.3.0"`. So when that comes out, the version would be later than your fork and would be used instead. I.e. basically inserting some extra versions into the list. I am not a maintainer/committer here so I can't promise that the next version would be `v"2.3.0"` but maybe the maintainers here could accomodate that if you want to go this route.

**Comment by NHDaly** [comment]
Hah, yeah cool. For better or worse we just have one big monorepo with only one manifest, so it's not a problem for us to build against the fork, but thanks, that's a super interesting idea if we ever changed to that approach!! ♥️ thanks for all the info Eric, this is helpful.

Hope you've been doing well!! ☺️☺️

**Comment by quinnj** [comment]
It shouldn't be too long; I think we're just waiting on @jrevels to sign the CLA and then we can make the transfer.

**Comment by NHDaly** [comment]
Cool, thanks Jacob! :) Lemme know if you want to chat about this at all when you're ready. 👍

**Comment by jrevels** [comment]
xref https://github.com/JuliaData/Arrow.jl/issues/265#issuecomment-998993831, hopefully we're one step closer to unblocking this :) happy to see that Relational is also making use of Arrow.jl!

**Review by quinnj — DISMISSED** [review]
Hmmm......yeah, I guess this is ok. I don't love the magical "text transformation" to make it plural, but I'm not sure there are many other better ideas. I had wanted to eventually split this out into a separate package or something, but perhaps we should just make a push to put in Base and be able to resolve the performance problems there perhaps.

**Comment by quinnj** [comment]
@kou, can you approve the tests running here and if passing, merge please?

**Comment by kou** [comment]
@quinnj Sure! But #273 blocks running CI. Please wait for a response from INFRA.

**Comment by quinnj** [comment]
Ah yes, I forgot those aren't enabled yet. Ok, we'll wait.

**Comment by NHDaly** [comment]
> I don't love the magical "text transformation" to make it plural, but I'm not sure there are many other better ideas.

One better text transformation which would be more reliable than the pluralization could be to rename `@enum Foo` to `FooModule` or `FooEnums` if you think you might prefer it? I agree this is a bit stinky.

But thanks for the approval, yeah, i didn't think of any better alternatives either. 👍

**Review by kou — APPROVED** [review]

**Comment by kou** [comment]
CI is runnable again.

**Review by kou — APPROVED** [review]
+1

CI is green.

**Comment by NHDaly** [comment]
Hooray. Thanks!

How will the release process work under the new setup? Should I have bumped a version number in my PR? Or will you do that separately afterwards?

**Pull request merged**
