### PR TITLE
fromarrow(::Type{Dates.Time}, x::Arrow.Time)

### LINKED ISSUE #363: Error when open files with Date.Time containing MICROSECONDs
When opening a table that contains a `Time` object containing `MICROSECONS` (which I think is the default with `python`/`pandas`) I get an error.

Example:
1. Create `python`/`pandas` dataframe:
    ```python
    pd.DataFrame(dict(
      i=range(0,10),
      time=[datetime.time(hour=i) for i in range(0,10)]
    )).to_feather('~/python_time_df.arrow')
    ```
1. read file in `julia`:
    ```julia
    tb = Arrow.Table("~/python_time_df.arrow", convert=true)
    tb.time
    ```
    yields the error
```
Failed to show value:
MethodError: no method matching Int64(::Arrow.Time{Arrow.Flatbuf.TimeUnits.MICROSECOND, Int64})
Closest candidates are:
(::Type{T})(!Matched::AbstractChar) where T<:Union{Int32, Int64} at char.jl:51
(::Type{T})(!Matched::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
(::Type{T})(!Matched::BigInt) where T<:Union{Int128, Int16, Int32, Int64, Int8} at gmp.jl:359
...

    - Dates.Time(::Arrow.Time{Arrow.Flatbuf.TimeUnits.MICROSECOND, Int64}, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Dates.AMPM)@types.jl:412
    - fromarrow(::Type{Dates.Time}, ::Arrow.Time{Arrow.Flatbuf.TimeUnits.MICROSECOND, Int64})@ArrowTypes.jl:157
    - fromarrow(::Type{Union{Missing, Dates.Time}}, ::Arrow.Time{Arrow.Flatbuf.TimeUnits.MICROSECOND, Int64})@ArrowTypes.jl:161
    - getindex@primitive.jl:46[inlined]
    - _getindex@abstractarray.jl:1274[inlined]
    - getindex@abstractarray.jl:1241[inlined]
    - isassigned(::Arrow.Primitive{Union{Missing, Dates.Time}, Vector{Arrow.Time{Arrow.Flatbuf.TimeUnits.MICROSECOND, Int64}}}, ::Int64, ::Int64)@abstractarray.jl:565
    - alignment(::IOContext{IOBuffer}, ::AbstractVecOrMat, ::Vector{Int64}, ::Vector{Int64}, ::Int64, ::Int64, ::Int64, ::Int64)@arrayshow.jl:68
    - _print_matrix(::IOContext{IOBuffer}, ::AbstractVecOrMat, ::String, ::String, ::String, ::String, ::String, ::String, ::Int64, ::Int64, ::UnitRange{Int64}, ::UnitRange{Int64})@arrayshow.jl:207
    - print_matrix(::IOContext{IOBuffer}, ::Arrow.Primitive{Union{Missing, Dates.Time}, Vector{Arrow.Time{Arrow.Flatbuf.TimeUnits.MICROSECOND, Int64}}}, ::String, ::String, ::String, ::String, ::String, ::String, ::Int64, ::Int64)@arrayshow.jl:171
    - print_array@arrayshow.jl:358[inlined]
    - show(::IOContext{IOBuffer}, ::MIME{Symbol("text/plain")}, ::Arrow.Primitive{Union{Missing, Dates.Time}, Vector{Arrow.Time{Arrow.Flatbuf.TimeUnits.MICROSECOND, Int64}}})@arrayshow.jl:399
    - show_richest(::IOContext{IOBuffer}, ::Any)@PlutoRunner.jl:1157
    - show_richest_withreturned@PlutoRunner.jl:1095[inlined]
    - format_output_default(::Any, ::Any)@PlutoRunner.jl:995
    - var"#format_output#60"(::IOContext{Base.DevNull}, ::typeof(Main.PlutoRunner.format_output), ::Any)@PlutoRunner.jl:1012
    - formatted_result_of(::Base.UUID, ::Base.UUID, ::Bool, ::Vector{String}, ::Nothing, ::Module)@PlutoRunner.jl:905
    - top-level scope@WorkspaceManager.jl:476
```

Defining
```julia
ArrowTypes.fromarrow(::Type{Dates.Time}, x::Arrow.Time{Arrow.Flatbuf.TimeUnits.MICROSECOND, Int64}) = convert(Dates.Time, x)
```
seems to fix the error.

### LINKED ISSUE #526: missing methods for `fromarrow(::Type{Time}, x::Arrow.Time{<:Arrow.Flatbuf.TimeUnit.T, <:Integer})`
I did not create table in question, but the column in question contains a time stored as `Arrow.Time{Arrow.Flatbuf.TimeUnit.MICROSECOND, Int64}` which errors upon access.

This can be fixed by adding the methods

```julia
function fromarrow(::Type{Time}, x::Arrow.Time{Arrow.Flatbuf.TimeUnit.MICROSECOND, <:Integer})
   return Time(0, 0, 0) + Microsecond(x.x)
end

function fromarrow(::Type{Time}, x::Arrow.Time{Arrow.Flatbuf.TimeUnit.MILLISECOND, <:Integer})
    return Time(0, 0, 0) + Millisecond(x.x)
 end

 function fromarrow(::Type{Time}, x::Arrow.Time{Arrow.Flatbuf.TimeUnit.NANOSECOND, <:Integer})
    return Time(0, 0, 0) + Nanosecond(x.x)
 end

 function fromarrow(::Type{Time}, x::Arrow.Time{Arrow.Flatbuf.TimeUnit.SECOND, <:Integer})
    return Time(0, 0, 0) + Second(x.x)
 end
```

I can open a PR adding these methods if there is no other preferred solution

### PR DESCRIPTION
**Pull request by palday**
- closes #526 
- closes #363

### CODE REVIEW

**Review by ericphanson — COMMENTED** [review]
what is different here from
```julia
ArrowTypes.fromarrow(::Type{Dates.Date}, x::DATE) = convert(Dates.Date, x)
```
above? Or is that method wrong too?

**Comment by ericphanson** [comment]
ahh, I get it, we are just dropping a type parameter, `TIME` is `Arrow.Time` with a specific eltype. Ok this seems fine to me!

**Comment by palday** [comment]
That method is probably wrong too

**Comment by ericphanson** [comment]
do you want to fix that one too? Or file an issue?

**Comment by palday** [comment]
Might as well fix it too while I'm at -- I'll update it shortly

**Comment by palday** [comment]
I was unable to induce the related failure with `DATE` so it seems that it is not broken for reasons beyond my understanding. In other words, I think this is good to go.

**Review by ericphanson — APPROVED** [review]

**Pull request merged**
