### PR TITLE
Implement Tables.columnnames and Tables.schema for Arrow.Stream

### PR DESCRIPTION
**Pull request by baumgold**

### CODE REVIEW

**Review by quinnj — APPROVED** [review]

**Comment by baumgold** [comment]
@kou - Could you please kick-off a new minor release?  I'm working to get my PGP key added to [KEYS](https://dist.apache.org/repos/dist/release/arrow/KEYS) so I can kick-off releases myself, but have yet to figure out how to join the Web of Trust ([link](https://www.cryptnet.net/fdp/crypto/keysigning_party/en/keysigning_party.html)).  Thanks.

**Comment by kou** [comment]
> Could you please kick-off a new minor release?

Sure! Could you open a pull request to bump version to suitable version like #377 ?

> I'm working to get my PGP key added to [KEYS](https://dist.apache.org/repos/dist/release/arrow/KEYS) so I can kick-off releases myself, but have yet to figure out how to join the Web of Trust ([link](https://www.cryptnet.net/fdp/crypto/keysigning_party/en/keysigning_party.html)). Thanks.

Could you send this to `dev@arrow.apache.org`? Someone will help us like https://lists.apache.org/thread/1f043ctx6k7ntkvqbwoo9y6bfgx5o7zf .

**Comment by baumgold** [comment]
> Sure! Could you open a pull request to bump version to suitable version like #377 ?

#406

> Could you send this to `dev@arrow.apache.org`? Someone will help us

Done, thanks!

**Comment by kou** [comment]
Thanks! I'll sign for the next release. But you'll be able to do it for the future releases.

**Comment by kou** [comment]
Vote thread: https://lists.apache.org/thread/15lpol0k1yv5kkl0mczobpwd4zmj6k0j

**Comment by kou** [comment]
Passed: https://lists.apache.org/thread/pjgy9d3b5zwzdzsl1trd2ylh1wmxhstb

Published:
* https://dist.apache.org/repos/dist/release/arrow/arrow-julia-2.5.0/
* https://github.com/apache/arrow-julia/commit/4d71bee55249dae32983971362256798a9af38bf#commitcomment-104658698

@ericphanson When the 2.5.0 tag is created? After https://github.com/JuliaRegistries/General/pull/79695 is merged?

**Comment by kou** [comment]
Tagged https://github.com/apache/arrow-julia/releases/tag/v2.5.0 after https://github.com/JuliaRegistries/General/pull/79695 is merged.

**Pull request merged**
