### PR TITLE
Bump version to 2.3.0

### PR DESCRIPTION
**Pull request by quinnj**
@kou, can we start a new minor version release process? Thanks!

### CODE REVIEW

**Review by kou — APPROVED** [review]
Sure.

**Comment by kou** [comment]
The vote thread: https://lists.apache.org/thread/66v4nrp4n1vmzmwcmhf9n9b4kv25jwgk

**Comment by kou** [comment]
@quinnj The vote carried: https://lists.apache.org/thread/7vrmt956dfcm04nz9pn2bt70mf1vb3p1
I've published the voted archive to https://dist.apache.org/repos/dist/release/arrow/arrow-julia-2.3.0/ .

Could you publish this release to the Julia General registry?

**Comment by quinnj** [comment]
New package versions submitted to General registry: https://github.com/JuliaRegistries/General/pull/58479

**Comment by kou** [comment]
Thanks!

**Pull request merged**
