### PR TITLE
Bump Arrow & ArrowTypes versions

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by quinnj** [comment]
@baumgold / @Moelf, I'm assuming we'd like to get a patch fix out quickly for the 2.6 errors we uncovered?

**Comment by Moelf** [comment]
yes, this would be great! thanks for the swift response

**Review by baumgold — APPROVED** [review]

**Comment by baumgold** [comment]
@kou - could you please kick-off a release vote?  Thank you.

**Comment by kou** [comment]
Sure!

**Comment by kou** [comment]
The vote thread: https://lists.apache.org/thread/rm0f25dx6z1b8wb0rf228mzs2zr6vyr2

**Comment by kou** [comment]
Passed: https://lists.apache.org/thread/woj7bdkr4z1mp5ltlw8pmqwkvdb19157

And I've released.

**Pull request merged**
