### PR TITLE
Make DictEncoding reading threadsafe

### LINKED ISSUE #534: Reading multiple file corrupt values and is also order dependent
```julia
flist1 = filter(contains("physics_TLA"), readdir("/data/jiling/TLA/julia_arrows/"; join=true))
flist2 = filter(contains("mRp20"), readdir("/data/jiling/TLA/julia_arrows/"; join=true))

Arrow.Table(flist1).proc |> unique
# 1-element Vector{Bool}:
# 0

Arrow.Table(flist2).proc |> unique
# 1-element Vector{Bool}:
# 1

length(Arrow.Table([flist1;]).proc), length(Arrow.Table([flist2;]).proc)
# (3000521, 10077)

length(Arrow.Table([flist1; flist2]).proc)
# 3010598

Arrow.Table([flist1; flist2]).proc |> unique
#1-element Vector{Bool}:
# 1
Arrow.Table([flist2; flist1]).proc |> unique
#1-element Vector{Bool}:
# 0

### PR DESCRIPTION
**Pull request by quinnj**
Fixes #534

### CODE REVIEW

**Comment by Moelf** [comment]
can we have a new release?

**Comment by quinnj** [comment]
We've kicked off a new voting period for a new release: https://github.com/apache/arrow-julia/commit/a4757d657a0a49b509ae582662f395ce154dd8be

**Comment by Moelf** [comment]
voting?

**Comment by quinnj** [comment]
Yeah, it's a mandate of "the apache way". new release should be out soon

**Pull request merged**
