### PR TITLE
bump version of Arrow and ArrowTypes to prepare for new release

### PR DESCRIPTION
**Pull request by baumgold**
I think we've merged enough PRs that we should probably cut a release.

### CODE REVIEW

**Review by quinnj — APPROVED** [review]

**Comment by baumgold** [comment]
@quinnj - Looks like one test failed in one of the builds.  I don't understand why.  Do you?

@kou - can you please kick-off a vote for two new releases, one for Arrow and one for ArrowTypes?  Thanks!

**Comment by quinnj** [comment]
Yes, just a rare intermittent flaky test; I think there's an open issue for it. I'm planning on doing something about it eventually, but not too worried about it in the mean time. It has to do w/ writing a bunch of batches in a specific order where a dict-encoded column starts out as one size and then needs to promote to a larger type later, but we get a weird error.

**Comment by kou** [comment]
Sure!

**Comment by kou** [comment]
The vote thread: https://lists.apache.org/thread/k32qqw9p1ltbrvwrrz3hrwbglqn23pby

**Comment by kou** [comment]
Passed: https://lists.apache.org/thread/cstnh7z0qr80yc88vnwf9nsh44dsk85f

(I hope that @baumgold and @ericphanson join a vote next time to be a PMC member.)

Kicked JuliaRegistrator: https://github.com/apache/arrow-julia/commit/771db0a31685e6b12e8b576685b7d8d5c573b855

**Comment by baumgold** [comment]
@kou - Just voted.  I hope my late vote still counts!  Thanks for making the release happen.

**Pull request merged**
