### PR TITLE
Bump version for release

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Review by kou — APPROVED** [review]
+1

I'll start a vote with this revision.

**Comment by kou** [comment]
2.2.1 RC1 VOTE thread: https://lists.apache.org/thread/1tkwh8j8hz6mbqj7qgot3v4qjpmpgdzv

**Comment by kou** [comment]
@quinnj It seems that some integration tests are failed on macOS 11.6 arm64:

https://lists.apache.org/thread/4ov70cjxch08ywysmwwmhckp9oqclc5z

> I failed to verify this on macOS 11.6 arm64. 3 integration tests crashed
> with "ArgumentError: unsafe_wrap: pointer 0x13b640ef8 is not properly
> aligned to 16 bytes".
>
> I don't know enough to know whether this is a problem with the integration
> test setup (and thus probably not release blocking) or whether it is
> something more critical.

Do you think that this is a release blocker?

**Comment by kou** [comment]
It seems that Julia itself is experimental on macOS arm64:

https://julialang.org/downloads/

> macOS ARM (M-series Processor) [help] | 64-bit (experimental)

**Comment by quinnj** [comment]
No, as listed [here](https://julialang.org/downloads/), macOS ARM is currently at Tier 3 language support, so it's not expected to be 100% functional.

**Comment by kou** [comment]
OK.

**Comment by kou** [comment]
@quinnj The vote carried and I've published the artifacts to https://dist.apache.org/repos/dist/release/arrow/arrow-julia-2.2.1/ .

Could you register this revision to the General registry? Or can I do it?

**Comment by quinnj** [comment]
It looks like we need the JuliaRegistrator GitHub App installed for this repo:

image

**Comment by quinnj** [comment]
I've submitted a request to update the package url in the General registry: https://github.com/JuliaRegistries/General/pull/56180. Afterwards, I've been told it's possible to register a new version via https://juliahub.com/ui/Registrator without needing to install the app for the organization.

**Comment by quinnj** [comment]
Ok, version was successfully submitted to the General registry, merged, and release tag made in this repo. I seem unable, however, to be able to use the same juliahub link above to tag a new release for the ArrowTypes subpackage.

**Pull request merged**
