### PR TITLE
bump version for new release

### PR DESCRIPTION
**Pull request by baumgold**
Includes the bug-fix from #453 / #454

### CODE REVIEW

**Review by ericphanson — APPROVED** [review]
ty!

**Comment by kou** [comment]
Sure!
But can we release `Arrow` too? Our release process doesn't support `ArrowTypes` only release yet.
See also: https://github.com/apache/arrow-julia/pull/407#issuecomment-1472754916

**Comment by kou** [comment]
OK!
The vote thread: https://lists.apache.org/thread/78q1rpd88t5zmcvtr742549wm7g5r51s

**Comment by kou** [comment]
Passed: https://lists.apache.org/thread/bfzng91j51vo3ygtsh8fzl5fmc3kcy2z

**Pull request merged**
