### PR TITLE
Bump Arrow + ArrowTypes versions

### PR DESCRIPTION
**Pull request by baumgold**

### CODE REVIEW

**Comment by baumgold** [comment]
@kou - Can you please help out with a release of ArrowTypes as well?  Thanks.

**Comment by kou** [comment]
Sure! But our release process doesn't support `ArrowTypes` only release yet.
Can we also release `Arrow`?
See also: https://github.com/apache/arrow-julia/issues/376#issuecomment-1381414099

**Comment by baumgold** [comment]
> Sure! But our release process doesn't support `ArrowTypes` only release yet. Can we also release `Arrow`? See also: [#376 (comment)](https://github.com/apache/arrow-julia/issues/376#issuecomment-1381414099)

Sure, that should be okay I think.

**Comment by baumgold** [comment]
@kou - Picking this back up again.  I bumped the version of both Arrow and ArrowTypes.  Is this still the correct thing to do in order to trigger an ArrowTypes release?  If so then I'll merge this PR so you can start a vote.  Thanks.

**Comment by kou** [comment]
Yes!

**Comment by baumgold** [comment]
@kau - I don't yet see the new release of ArrowTypes.  I expect to see v2.1.0 in the [JuliaRegistry](https://github.com/JuliaRegistries/General/blob/master/A/ArrowTypes/Versions.toml), but it doesn't look like it's there yet.

**Comment by kou** [comment]
@ericphanson Could you help us? I think that we may need to change how we use ` @JuliaRegistrator register()`: https://github.com/apache/arrow-julia/commit/686ab570b831035715cb58f666233ec673e50d8f#commitcomment-109739320

**Comment by baumgold** [comment]
@kou - I believe we just have to explicitly register the sub-package by adding the followiong comment [here](https://github.com/apache/arrow-julia/commit/686ab570b831035715cb58f666233ec673e50d8f):

```@JuliaRegistrator register subdir=src/ArrowTypes```

I don't have permissions to do so.  Can you try, please?  Thanks.

**Comment by kou** [comment]
Done: https://github.com/apache/arrow-julia/commit/686ab570b831035715cb58f666233ec673e50d8f#commitcomment-110073911

**Pull request merged**
