### PR TITLE
Add reading metadata from Arrow.Table

### PR DESCRIPTION
**Pull request by bkamins**
Partially solves https://github.com/apache/arrow-julia/issues/337 for `Arrow.Table`.

### CODE REVIEW

**Comment by bkamins** [comment]
bump

@quinnj - there are recurring requests for this functionality

**Comment by asinghvi17** [comment]
Bump - would it be possible to get this PR in, even if only for tables?

**Comment by evetion** [comment]
Bump, this would be really useful for ecosystem integration.

**Review by nalimilan — APPROVED** [review]

**Review by quinnj — APPROVED** [review]
Sorry for the delay on this!

**Pull request merged**
