### PR TITLE
Bump version to 2.7.3

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by quinnj** [comment]
@kou, can you help us kickoff a new release?

**Comment by kou** [comment]
Sure! I'll do it.

**Comment by kou** [comment]
The vote thread: https://lists.apache.org/thread/ldkmmmj7cj2y3qp3xfd15pf1dr7bds15

**Comment by kou** [comment]
Passed: https://lists.apache.org/thread/j2r22ljry35wpqk8wolo8fwyj5wtsc4x

I've published.

**Pull request merged**
